### ISSUE TITLE
翻译错误：1.1 进程和内存

### ISSUE THREAD

**Issue by davisday227** [OGman/xv6-book-riscv-rev1-Chinese#1]
在1.1 进程和内存章节中，英文原文如下：
In the parent, fork returns the child’s PID; in the child, fork returns zero.
翻译如下：
在父进程中，fork返回子进程的PID；在进程中则返回0。

原文中，突出了在child即子进程，而翻译为进程，我认为应该保留原意突出子进程

**Comment by OGman** [comment]
很好的建议，已修改
