### ISSUE TITLE
翻译错误：1.2 I/O与文件描述符

### ISSUE THREAD

**Issue by davisday227** [OGman/xv6-book-riscv-rev1-Chinese#2]
句子“fork将父进程的文件描述符表同它的内存一起拷贝，这样子进程开始时就拥有预付金诚完全相同的打开的文件”内有输入法错误，“预付金诚”应为“与父进程”。

原文：Fork copies the parent’s file descriptor table along with its memory, so that the child starts with exactly the same open files as the parent.

**Comment by OGman** [comment]
已修复，多谢指正
